apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-echo-go-cert
spec:
  secretName: my-echo-go-tls-secret
  subject:
    organizations:
      - iam.azssi
    countries:
      - KR
  commonName: azssi.dev
  usages:
    - "server auth"
  dnsNames:
    - my-echo-go
  ipAddresses:
    - 172.22.11.2
  issuerRef:
    name: my-echo-go-issuer
    kind: Issuer
    group: cert-manager.io
