name: GCP integration test

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - run: gcloud info

    - name: check gsutil
      run: |-
        env
        df -h
        gsutil ls
